<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

//class TestRequest extends \Dingo\Api\Http\FormRequest
class TestRequest extends FormRequest
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Prepare the data for validation.
     *
     * @return void
     */
    protected function prepareForValidation()
    {
        parent::prepareForValidation();

        \Log::info('prepareForValidation');
    }

    public function withValidator($validator)
    {
        \Log::info('withValidator');
    }


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        \Log::info('rules()');
        return [
            'test' => 'required',
        ];
    }

    public function validated()
    {
        \Log::info('validated()');
        return parent::validated(); // TODO: Change the autogenerated stub
    }
}
